spring:
  application:
    name: FirmManagementPet
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/migration/init_changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/firm_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  #  security:
  #    user:
  #      name: admin
  #      password: admin
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true